# Generated by Django 5.0.6 on 2024-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proiezione',
            name='posti_disponibili',
            field=models.IntegerField(default=20),
        ),
    ]
